apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
    name: {TOPIC_NAME}

---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
    name: {DEADLETTER_TOPIC_NAME}
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: {SUBSCRIPTION_NAME}
spec:
    ackDeadlineSeconds: {ACK_DEADLINE_SECONDS} 
    messageRetentionDuration: {MESSAGE_RETENTION_DURATION}
    retainAckedMessages: {TRUE,FALSE}
    topicRef:
        name: {TOPIC_NAME}
    deadLetterPolicy:
        deadLetterTopicRef:
            name: {DEADLETTER_TOPIC_NAME}
    retryPolicy:
        minimumBackoff: {MINIMUM_BACKOFF}
        maximumBackoff: {MAXIMUM_BACKOFF}
    expirationPolicy:
        ttl: {TTL}
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: {DEADLETTER_SUBSCRIPTION_NAME}
spec:
  topicRef:
      name: {DEADLETTER_TOPIC_NAME}
