apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: {$PUBSUB?}-topic
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: {$PUBSUB?}-subscription
  labels:
    goog-dm: d1
spec:
  topicRef:
    name: {$PUBSUB?}-topic
  ackDeadlineSeconds: 60
  messageRetentionDuration: "1200s"
  retainAckedMessages: true
  expirationPolicy:
    ttl: "86400s"
